// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzdCpgZ_ErOvnbLjIvt0zVC4eUrbCwq8',
    appId: '1:195512524145:web:4819a04101c45e0a79ead0',
    messagingSenderId: '195512524145',
    projectId: 'grabit-vendor-app-2026',
    authDomain: 'grabit-vendor-app-2026.firebaseapp.com',
    storageBucket: 'grabit-vendor-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEe_m-SvPDR5fGqJBMFrYHDn7YoSnu-a4',
    appId: '1:195512524145:android:aa2e3209790269c879ead0',
    messagingSenderId: '195512524145',
    projectId: 'grabit-vendor-app-2026',
    storageBucket: 'grabit-vendor-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmggBwCwWKf0JZG5TUM_zE7alPwo3Szfg',
    appId: '1:195512524145:ios:066c5b445c4b2a9079ead0',
    messagingSenderId: '195512524145',
    projectId: 'grabit-vendor-app-2026',
    storageBucket: 'grabit-vendor-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.grabIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmggBwCwWKf0JZG5TUM_zE7alPwo3Szfg',
    appId: '1:195512524145:ios:066c5b445c4b2a9079ead0',
    messagingSenderId: '195512524145',
    projectId: 'grabit-vendor-app-2026',
    storageBucket: 'grabit-vendor-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.grabIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkzdCpgZ_ErOvnbLjIvt0zVC4eUrbCwq8',
    appId: '1:195512524145:web:7c75ce3008298b7c79ead0',
    messagingSenderId: '195512524145',
    projectId: 'grabit-vendor-app-2026',
    authDomain: 'grabit-vendor-app-2026.firebaseapp.com',
    storageBucket: 'grabit-vendor-app-2026.firebasestorage.app',
  );
}
